### ISSUE TITLE
Not to backup to iCloud Options(iOS)

### ISSUE THREAD

**Issue by ericyu76** [brodysoft/Cordova-SQLitePlugin#143]
Is there possible to add not to backup to iCloud as an options? I'm facing the Apple reject by this reason. We actually no need to backup to iCloud, is there any workaround?

**Comment by tannerlinsley** [comment]
Any word on this?  This is really important to a lot of devs that can't get their app approved.  I'm using PouchDB on cordova and this plugin is awesome, but needs this options asap.

**Comment by dilignt** [comment]
@tannerlinsley - I managed to get my app approved by changing the `NSDocumentDirectory` reference to `NSLibraryDirectory` on line 172 of SQLitePlugin.m.  I don't know why this isn't the default - it should be an enhancement to turn iCloud backup on rather than off IMO

Don't forget to also add `<preference name="BackupWebStorage" value="none"/>` to your config.xml.

Hope this helps

**Comment by brodybits** [comment]
Thanks guys! I am planning to make the solution in the next couple weeks or
so (I will try to make it sooner but cannot make any promises due to some
business distractions).

What I am thinking is to add an optional parameter to specify the documents
path, according to the Cordova File api (but avoiding the dependency,
unless absolutely necessary).

I would also favor the default NOT to be sync'd to iCloud, but with
consideration that this would be a BREAKING CHANGE to existing (iOS) apps
(I did already make a breaking change to the Android version last year).

For now I give the solution as described by @Diligent as the workaround.

@brodybits

On Tuesday, January 20, 2015, Dilignt Ltd <notifications@github.com> wrote:

> @tannerlinsley <https://github.com/tannerlinsley> - I managed to get my
> app approved by changing the NSDocumentDirectory reference to
> NSLibraryDirectory on line 172 of SQLitePlugin.m. I don't know why this
> isn't the default - it should be an enhancement to turn iCloud backup on
> rather than off IMO
>
> Don't forget to also add <preference name="BackupWebStorage"
> value="none"/> to your config.xml.
>
> Hope this helps
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brodysoft/Cordova-SQLitePlugin/issues/143#issuecomment-70752309>
> .
>


-- 
Sent from my mobile

**Comment by brodybits** [comment]
Hi @svapreddy it *should* be possible to build the WP(8) version to run on WP7 as well (using the CSharp-SQLite classes) but I have not been able to test it. If you (or someone else) could try to run it on WP7 and send a pull request if it works, it may help someone else :smile:

**Comment by n40jpj** [comment]
Ok I have a working solution which I am just about to upload to Apple. This is taking some information from the above link, and from applying a bit of common sense.

Step 1 : Find the file SQLitePlugin.m and go to line 170 ish. Now put the below lines:

NSArray *paths = NSSearchPathForDirectoriesInDomains(NSLibraryDirectory, NSUserDomainMask, YES);
NSString *libraryDirectory = [paths objectAtIndex:0];
libraryDirectory = [libraryDirectory stringByAppendingString:@"/NoCloud"];
NSError *err = nil;
[self setAppDocsPath:libraryDirectory];

In place of :

NSString *docs = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) objectAtIndex: 0];
NSLog(@"Detected docs path: %@", docs);
[self setAppDocsPath:docs];

What this does is to tell the SQLitePlugin where to look for your database. The bit you are still missing is to get dbcopy to copy the .db file from the resources directory into the correct directory on the phone. To do this I did the following:

Step 2: Find and open the plugin file sqlDB.m:

Find the below:

paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
documentsDirectory = [paths objectAtIndex:0];

Replace with :

NSArray *paths = NSSearchPathForDirectoriesInDomains(NSLibraryDirectory, NSUserDomainMask, YES);
NSString *libraryDirectory = [paths objectAtIndex:0];
libraryDirectory = [libraryDirectory stringByAppendingString:@"/NoCloud"];

That's it your app is back into a working state and now uses the Library/NoCloud directory rather than the Documents directory on the iphone.

I'll let you know if this solves the issues for Apples tests.

**Comment by brodybits** [comment]
I have just pushed a new release to master with this feature. Please see README.md for usage. The plugin creates a new `LocalDatabase` subdirectory under `Library`, with the iCloud backup disabled, and uses the new subdirectory *only* if the `location` option with value of `2` is used in `openDatabase`. If you encounter any problems please log a new issue.

**Comment by dilignt** [comment]
This fix is wrong - there should be an option to disable backup to iCloud
without using the openDatabase call, and the default should have backup
off, not on.  Using this plugin with PouchDB gives me no option to disable
backup without editing 3rd party source code, either PouchDB or the plugin.


I fixed this issue in the previous version by changing NSDocumentDirectory
to NSLibraryDirectory in the source, but this no longer works and I'm back
to square one.

Please disable the backup to iCloud

**Comment by blablapolicja** [comment]
@brodybits what if I use pre-populated DB? I need to disable iCloud back-up. Will this code work? 
```
db = sqlitePlugin.openDatabase({name: "db.db", createFromLocation: 2});
```
in Xcode console I get 
```
open full db path: /var/mobile/Containers/Data/Application/FCD72BA1-DF71-420A-95E5-95414ECEFD83/Documents/db.db
```
Thank you in advance

**Comment by brodybits** [comment]
On Mar 16, 2015 9:54 PM, "Stanislav Dzhus" <notifications@github.com> wrote:
>
> @brodybits what if I use pre-populated DB? I need to disable iCloud
back-up. Will this code work?
>
> db = sqlitePlugin.openDatabase({name: "db.db", createFromLocation: 2});

In your case you have to include both location and createFromLocation
options. Also you gave the wrong value for the createFromLocation option.

To fix your code:

    db = sqlitePlugin.openDatabase({name: "db.db", location: 2,
createFromLocation: 1});

I will make this more clear in the readme. Please report if it still does
not work.

Chris

**Comment by blablapolicja** [comment]
I used your fix
now my DB copied to /Library/LocalDatabase/ 
but I get
```
DB opened: db.db
{"code":5,"message":"no such table: stores"}
```

**Comment by brodybits** [comment]
Make sure your db file does not already exist (in the target directory).

I made an example pre-populated db project (Android version only) at: https://github.com/brodybits/Cordova-pre-populated-db-example-android

**Comment by blablapolicja** [comment]
it works! thank you
I deleted my app from device, and then build/run again

**Comment by brodybits** [comment]
Thanks happy to hear!

**Comment by svapreddy** [comment]
:+1:
