### ISSUE TITLE
Transaction object is getting lost

### ISSUE THREAD

**Issue by stshivam** [brodysoft/Cordova-SQLitePlugin#160]
I am using this plugin for one of my phonegap project. I am facing issue with the database transaction object. I am calling one android activity from javascript and after finishing that activity, i am trying to  access database using "db.transaction" call, but it is unable to call the transaction and it is not giving any error also. After debugging, when i commented line 1 & 2, it started to work but now sometimes transaction call is behaving randomly.

SQLitePlugin.prototype.addTransaction = function(t) {
    this.txQ.push(t);
    if (this.txQ.length === 1) {           ----->Line 1
      t.start();
    }                                                  ------>Line 2
  };

Kindly suggest me what exactly this code is doing.

**Comment by brodybits** [comment]
FYI there are two major advantages of this plugin on the Android platform: database will be in a known location (always) and there is no practical limitation to the database file size.

**Comment by nolanlawson** [comment]
@brodybits You're right; I'm sorry for being so glib. The known location thing is incredibly useful; pre-Android 4.4. you could actually tell the WebView where to store WebSQL databases, but post-4.4 that's not an option anymore.

**Comment by brodybits** [comment]
A less buggy sqlite plugin would be nice, though.

I suspect the issue #193 (Android not saving the inserts upon abnormal exit) is due to changes in [android / platform_external_sqlite](https://github.com/android/platform_external_sqlite) - I am thinking in commit [d4f30d0](https://github.com/android/platform_external_sqlite/commit/d4f30d0d1544f8967ee5763c4a1680cb0553039f). The workaround to close and reopen the db for every transaction (which I am planning to support in an `openDatabase` option) is pretty bad. Hopefully the Android team will fix it someday :smile:
