### ISSUE TITLE
[AppGyver] Build Error [implicit declaration of CDVNewBase64Encode]

### ISSUE THREAD

**Issue by bamsoda** [brodysoft/Cordova-SQLitePlugin#203]
I am using AppGyver Steroids build and getting the following error. I am not sure if anything changed recently on your side.

Plugins/com.brodysoft.sqlitePlugin/SQLitePlugin.m:576:26: error: implicit declaration of function 'CDVNewBase64Encode' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    char* outputBuffer = CDVNewBase64Encode(blob_chars, blob_length, true, &outputLength);

**Comment by brodybits** [comment]
SQLitePlugin.m includes NSData+Base64.h from Cordova, which *should* declare CDVNewBase64Encode. Please double-check your installation.

**Comment by madthew** [comment]
Hi I have the same problem... I wrote to appgyver support and they answered the following


Hey,
all plugins need to be compatible with 64bit architecture as required by Apple since February this year. From the error,t looks like the SQLite plugin is not, so you would need to fork it and update yourself, or wait for the author to update.

Did you manage to fix the problem? It really sucks I have to update an app that was compiling fine 2 months ago...!

**Comment by brodybits** [comment]
> I am using AppGyver Steroids build and getting the following error. I am
not sure if anything changed recently on your side.
>
> Plugins/com.brodysoft.sqlitePlugin/SQLitePlugin.m:576:26: error: implicit
declaration of function 'CDVNewBase64Encode' is invalid in C99
[-Werror,-Wimplicit-function-declaration]
> char* outputBuffer = CDVNewBase64Encode(blob_chars, blob_length, true,
&outputLength);

> Hi I have the same problem... I wrote to appgyver support and they
answered the following
>
> Hey,
> all plugins need to be compatible with 64bit architecture as required by
Apple since February this year. From the error,t looks like the SQLite
plugin is not, so you would need to fork it and update yourself, or wait
for the author to update.

This really needs to be fixed in the Cordova project itself. I am happy to
make the workaround later today or sometime next week.

Chris

**Comment by madthew** [comment]
Great thank you!

**Comment by brodybits** [comment]
Looking at SQLitePlugin.m and Cordova/NSData+Base64.h very carefully, I cannot see how this could be an issue in a properly installed Cordova iOS development/build environment. Looking at NSData+Base64.h here: https://github.com/apache/cordova-ios/blob/master/CordovaLib/Classes/NSData%2BBase64.h

- We see that CDVNewBase64Encode would be declared regardless of the CPU architecture.

Also looking at the Blame: https://github.com/apache/cordova-ios/blame/master/CordovaLib/Classes/NSData%2BBase64.h

- It appears that CDVNewBase64Encode was already defined in July 2012.

Please challenge AppGyver further since this has been declared in Cordova for over 2 years.

If you still cannot get a resolution, then I have to consider whether to use an #ifdef workaround or replace it with an embedded base64 library such as LIBB64.

**Comment by madthew** [comment]
I post here the thread on appgyver forum if anyone is interested....

https://forums.appgyver.com/#!/steroids-bugs:sqlite-plugin-build-failed

**Comment by harsaharsa** [comment]
Hey, AppGyver dev here! The plugin installed on my local machine running our iOS wrapper fine, so it looks like there's nothing wrong on the plugin side – we'll see what's going on in our build service. This issue can be closed.

**Comment by brodybits** [comment]
Thanks @harsaharsa, closing.
